### Arrays in display.conf #
function display() {
    print_step "Installing Display Drivers"

    local INSTALL_DRIVER_PACKAGES="" PACKAGES_DRIVER="" PACKAGES_DRIVER_MULTILIB=""
    local PACKAGES_DDX="" PACKAGES_VULKAN="" PACKAGES_VULKAN_MULTILIB=""
    local PACKAGES_HARDWARE_ACCELERATION="" PACKAGES_HARDWARE_ACCELERATION_MULTILIB=""

    #### Arrays in display.conf
    IFS=':' read -r INSTALL_DRIVER_PACKAGES PACKAGES_DRIVER PACKAGES_DRIVER_MULTILIB <<< "$(printf '%s' "${DISPLAY_DRIVER_DEPENDENCIES[$DISPLAY_DRIVER]}")"
    ### --- ###
    
    if [[ "$DISPLAY_DRIVER_DDX" == "true" && "$DISPLAY_DRIVER" != "virtio" && -n "$DISPLAY_DRIVER" ]]; then
        PACKAGES_DDX="xf86-video-${DISPLAY_DRIVER}"
    fi
    ### --- ###

    if [ "$VULKAN" == "true" ]; then
        IFS= ':' read -r PACKAGES_VULKAN PACKAGES_VULKAN_MULTILIB <<< "$(printf '%s' "${VULKAN_DEPENDENCIES[$DISPLAY_DRIVER]}")"
    fi
    ### --- ###

    if [[ 
        "$DISPLAY_DRIVER" == "intel" &&
        "$DISPLAY_DRIVER_HARDWARE_VIDEO_ACCELERATION" == "true" &&
        -n "$DISPLAY_DRIVER_HARDWARE_VIDEO_ACCELERATION_INTEL" ]]; then

            PACKAGES_HARDWARE_ACCELERATION="$DISPLAY_DRIVER_HARDWARE_VIDEO_ACCELERATION_INTEL"
            PACKAGES_HARDWARE_ACCELERATION_MULTILIB=""

    elif [ "$DISPLAY_DRIVER_HARDWARE_VIDEO_ACCELERATION" == "true" ]; then
        IFS= ':' read -r PACKAGES_HARDWARE_ACCELERATION PACKAGES_HARDWARE_ACCELERATION_MULTILIB <<< "$(printf '%s' "${HARDWARE_ACCELERATION_DEPENDENCIES[$DISPLAY_DRIVER]}")"
    fi
    ### --- ###

    if [ "$INSTALL_DRIVER_PACKAGES" == "true" ]; then
        pacman_install "mesa $PACKAGES_DRIVER $PACKAGES_DDX $PACKAGES_VULKAN $PACKAGES_HARDWARE_ACCELERATION"
    else
        aur_install "mesa $PACKAGES_DRIVER $PACKAGES_DDX $PACKAGES_VULKAN $PACKAGES_HARDWARE_ACCELERATION"
    fi
    ### --- ###

    if [ "$PACKAGES_MULTILIB" == "true" ]; then
        pacman_install "$PACKAGES_DRIVER_MULTILIB $PACKAGES_VULKAN_MULTILIB $PACKAGES_HARDWARE_ACCELERATION_MULTILIB"
    fi
}